version: "3.9"
services:
    database:
        image: mysql:5.7
        ports:
        - "3306:3306"
        environment:
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_USER=user
        - MYSQL_PASSWORD=password
        - MYSQL_DATABASE=demodb
    web:
        image: nginx
        ports:
        - "8080:80"